"""Human-authored lecture content, not generated marketing examples.

Each deck combines theory, a hand-check, a term spine, a code hand-off,
an assessed exercise, and an AI prompt with an explicit verification step.
External sources are reference targets, NOT falsely marked as fetched.

``math`` fields are matplotlib-mathtext strings (LaTeX subset); they are
rendered to transparent PNGs by the deck design system at build time.
"""

SOURCES = {
    'pytorch': ('PyTorch documentation', 'https://docs.pytorch.org/docs/stable/index.html'),
    'sklearn': ('scikit-learn: model evaluation', 'https://scikit-learn.org/stable/modules/model_evaluation.html'),
    'data': ('EHU: Hyperspectral Remote Sensing Scenes', 'https://www.ehu.eus/ccwintco/index.php/Hyperspectral_Remote_Sensing_Scenes'),
    'aviris': ('NASA/JPL AVIRIS instrument overview', 'https://aviris.jpl.nasa.gov/html/aviris.overview.html'),
    'svm': ('scikit-learn: SVC and preprocessing', 'https://scikit-learn.org/stable/modules/svm.html'),
    'hybrid': ('HybridSN author repository', 'https://github.com/gokriznastic/HybridSN'),
    'proto': ('Snell et al. Prototypical Networks, 2017', 'https://arxiv.org/abs/1703.05175'),
    'msp': ('Hendrycks & Gimpel: detection baseline, 2017', 'https://arxiv.org/abs/1610.02136'),
    'openmax': ('Bendale & Boult: Towards Open Set Deep Networks, 2016', 'https://arxiv.org/abs/1511.06233'),
    'cam': ('Selvaraju et al. Grad-CAM, 2017', 'https://arxiv.org/abs/1610.02391'),
    'focal': ('Lin et al. Focal Loss, 2017', 'https://arxiv.org/abs/1708.02002'),
    'reading': ('Keshav: How to Read a Paper', 'https://web.stanford.edu/class/ee384m/Handouts/HowtoReadPaper.pdf'),
    'repro': ('Pineau et al. Reproducibility, JMLR 2021', 'https://jmlr.org/papers/v22/20-303.html'),
}


def page(title, points, visual, notes, math=None, image=None, source=None, run=None):
    return dict(title=title, points=points, visual=visual, notes=notes,
                math=math, image=image, source=source, run=run)


# Images refer to notebook cell IDs, not machine-specific result paths.
GT = ('00_environment_check.ipynb', 'dataset', 0)
LESSONS = [
 dict(id='L00', slug='environment', title='先验证环境，再相信结果',
 subtitle='Kernel / Path / Data / Forward', prerequisites='会运行 Python；不用先懂神经网络',
 notebook='00_environment_check.ipynb', cells=['environment','dataset','forward'], assignment='A01',
 outputs=['环境版本报告','数据与标签检查','一次前向 shape 断言'],
 sources=['pytorch','data'],
 pages=[
 page('pip 安装成功，为什么仍然 import 失败？', ['终端 python 与 notebook kernel 常不是同一个环境','先打印 sys.executable，再谈依赖','本项目依赖在 .venv；kernel 指向错 = 装到别处'], ['终端解释器','Notebook kernel','实际运行环境'],
      '开场展示一个常见 import 错误。让学生现在就打印自己 kernel 的 sys.executable——这是本课程最常见的翻车点，输出因机器而异，关键是确认指向项目 .venv。',
      run=('import sys; print(sys.executable)', '<项目>\\.venv\\Scripts\\python.exe')),
 page('一次成功，分四层验证', ['数据存在 ≠ 键名正确','前向跑通 ≠ 模型有效','四层各有断言，不靠感觉'], ['Python','ROOT','MAT keys'],
      '逐项通过才能前进。键名 indian_pines_corrected/indian_pines_gt 写错时 loadmat 不报错而是 KeyError 或多一层列表——现场演示一次错误键名。',
      run=('cube.shape, gt.shape', '((145, 145, 200), (145, 145))')),
 page('项目根目录不是个人绝对路径', ['BOOT cell 从当前目录向父目录找 dataset/','从根目录或 notebooks/ 启动都应成功','个人 D 盘路径不进教材'], ['HSI-Learning','notebooks/','dataset/'],
      '现场从 notebooks/ 子目录启动 kernel，预测 ROOT 是否变化。BOOT cell 的逻辑就是逐级向父母录检查 dataset 标志。',
      run=('(Path.cwd() / "dataset").exists()', 'False  # 从 notebooks/ 启动时')),
 page('先检查数据，暂时不训练', ['cube 与 GT 的空间尺寸相同','0 表示未标注，不是无观测','保存数据版本与核验记录'], ['Cube','Ground truth','Data card'],
      '这张图来自已执行第0课，不是示意图。读出 shape、dtype、标签集合。', image=GT,source='data'),
 page('手算一个分类头输出', ['输入 batch 为 2','已知类别数为 16','输出包含 32 个 logits'], ['(2,12,9,9)','Classifier','(2,16)'],
      '把batch改成3，先说答案再运行。随机初始化输出只能证明接口正确。',math=r'B=2,\ C=16 \;\Rightarrow\; \mathrm{logits} \in \mathbb{R}^{2 \times 16}',
      run=('head(torch.randn(3, 12, 9, 9)).shape', 'torch.Size([3, 16])')),
 page('demo 与 train 是两种承诺', ['演示包不止权重：PCA/scaler/split/阈值','加载时校验 SHA256 与配置匹配','缺资产就明示，不偷偷训练'], ['配置 + 权重','预处理 + split','校验 + 推理'],
      '强调训练包不仅是pth。让学生打开 results/teaching_ready 下的 run_config.json 核对这三个值——加载不兼容权重应当失败。',
      run=("cfg['components'], cfg['patch_size'], cfg['seed']", '(12, 9, 42)')),
 ],
 code='print(sys.executable)\ncube, gt, names = load_hsi_dataset("IP", ROOT/"dataset")\nassert cube.shape[:2] == gt.shape\nassert logits.shape == (2, len(names))',
 change='把 batch 从2改成3，先写出预期形状，再运行断言。',
 ai='根据我提供的 sys.executable、异常堆栈和 requirements，列出可能原因及最小只读检查命令。不要安装、删除文件或猜测环境；证据不足标明待检查。',
 verify='逐条在当前kernel验证；不执行无法解释的安装/删除命令。',
 limits=['前向成功 ≠ 训练有效','本机验证 ≠ 所有平台保证']),

 dict(id='L01',slug='data',title='200 个波段，是 200 张照片吗？',subtitle='从数据立方体到一条光谱',
 prerequisites='L00：环境和路径已检查',notebook='01_data_reading_and_visualization.ipynb',cells=['loadmat','cube[:, :, b]','cube[r, c, :]'],assignment='A01',
 outputs=['一页数据卡','空间/光谱切片','GT与观测的区别'],sources=['data','aviris'],
 pages=[
 page('同样大小的两幅图，只有一幅是标签', ['观测是传感器记录','GT 是人工/调查监督信息','类别颜色不是材料真实颜色'], ['观测 X','标签 y','显示颜色'],
      '先让学生区分伪彩色与GT。GT不能作为分类输入的一部分。',image=GT,source='data'),
 page('观测图是三个波段的合成显示', ['真彩色只取三个波段映射到RGB','改变波段组合不改变数据本身','显示拉伸只影响人眼，不影响标签'], ['Band r/g/b','Stretch','GT 不变'],
      '真彩色合成来自notebook 03。问学生：换成(50,90,150)显示会怎样？显示选择是演示变量，不是实验变量。',image=('03_hybridsn_baseline.ipynb','cell5',0),source='data'),
 page('一个数组，两种视角', ['固定波段：一张 145×145 灰度图','固定位置：一条 200 维光谱向量','第三维不是类别轴'], ['H 行','W 列','B 波段'],
      '让学生对 toy 数组口算 shape，再对 IP 实测。ndarray 不自带物理轴语义。',
      math=r'X \in \mathbb{R}^{H \times W \times B}',
      run=('cube[:, :, 50].shape, cube[30, 40, :].shape', '((145, 145), (200,))')),
 page('不同波段，同一地物亮度不同', ['六个波段显示六种纹理','农田与道路在不同波段对比度不同','波段选择同时影响显示与可分性'], ['band 84','band 128','band 35'],
      '本图来自notebook 01的实际波段切片。band index不是波长：删带改变索引与波长对应，没有元数据不做nm换算。',image=('01_data_reading_and_visualization.ipynb','8482399b-633f-4fb3-922f-94cb5d0df5b1',0),source='aviris'),
 page('先预测 shape，再切片', ['X[:, :, b] → (H,W)','X[r,c,:] → (B,)','X[r,:,:] 是行切片，不是波段切片'], ['固定 b','空间切片','固定 r,c → 光谱'],
      'IP 实测形状 145×145×200 来自 dataset/README.md 的本地加载记录。给 3×4×5 toy 数组依次问 shape。',
      math=r'145 \times 145 \times 200',
      run=('cube[:, :, :3].transpose(2, 0, 1).shape', '(3, 145, 145)')),
 page('零标签不等于零信号', ['gt=0 是未标注，不是一类背景','已标注 10249 / 未标注 10776','最少类 Oats 只有 20 个样本，最多类 2455'], ['全部像元','有标注中心','监督损失'],
      '现场运行这条命令并读数：10249 个监督样本占总像元不到一半。20 与 2455 相差超过 120 倍——后面讲不均衡和开集的根子就在这里。',
      run=('(gt > 0).sum(), (gt == 9).sum()', '(10249, 20)')),
 ],
 code='band = cube[:, :, 50]\nspectrum = cube[30, 40, :]\nmask = gt > 0\nprint(band.shape, spectrum.shape, mask.sum())',
 change='只改变显示波段组合，验证样本数和GT完全不变。',
 ai='只依据给出的 MAT keys、shape、dtype 和来源片段生成数据卡。区分实测项与文献项；没有波长表时不要推断波长或红边位置。',
 verify='用loadmat与shape断言检查实测项；传感器/波长需要原始资料证据。',
 limits=['显示好看不等于数据可分','传感器参数不能替代本文件元数据']),

 dict(id='L02',slug='protocol',title='99% 准确率，为什么可能没有意义？',subtitle='划分、指标与信息边界',
 prerequisites='L01：观测/标签已区分',notebook='02_svm_baseline.ipynb',cells=['train_test_split','classification_report'],assignment='A02',
 outputs=['协议检查表','手算混淆矩阵','带边界的结果描述'],sources=['sklearn','repro'],
 pages=[
 page('先问分母，再问高分', ['先问分数算在哪些像元上','是否混入背景 0？','模型何时看过这些信息？'], ['样本集合','指标分母','可声称结论'],
      '展示一个分数但不展示协议，让学生提出必须追问的信息。',
      run=('len(y_test)  # 协议A', '2050')),
 page('三份数据，三种职责', ['train拟合、val选择、test报告','三份位置互斥、不重叠','随机划分在空间上是交错的'], ['Train','Val','Test'],
      '这是notebook 03协议B的train划分显示：三类样本在空间交错分布，因此9×9窗口很容易跨越划分共享观测——patch重叠问题直接在这张图上讲。',image=('03_hybridsn_baseline.ipynb','cell11',0)),
 page('总报大类，也能得到90% OA', ['A/B/C 样本数900/90/10','全部预测A','小类识别能力为零'], ['A:900 → A','B:90 → A','C:10 → A'],
      '明确这是人工构造算例，不是Indian Pines实测。手算OA和AA。',
      math=r'OA = \frac{900}{1000} = 0.90 \qquad AA = \frac{1+0+0}{3} = \frac{1}{3}',
      run=('accuracy_score(y, pred)  # 全预测A', '0.9')),
 page('Kappa不是“再算一次准确率”', ['p_o = p_e = 0.9 时 Kappa 必为 0','本章初稿曾把该例写成 0.47——错','手算与库函数都给出 0'], ['Observed .90','Expected .90','Kappa 0'],
      '这是本项目自己纠过的错：正确做法是手算+库函数双验证，不许只信一次推导。',
      math=r'\kappa = \frac{p_o - p_e}{1 - p_e} = \frac{0.90 - 0.90}{0.10} = 0',
      run=('cohen_kappa_score(y, pred)', '0.0')),
 page('混淆矩阵是指标的原图', ['对角线=分类正确的数量','每行是一个真实类，读support','小类是否全错看行，不看总分'], ['Rows = truth','Diagonal','Per-class recall'],
      '这是notebook 02在IP测试划分上的实测混淆矩阵。让学生指出错误最多的类、错成了谁。',image=('02_svm_baseline.ipynb','32e479d9-7018-4689-af9b-d70239566b14',0)),
 page('课程四套协议，数字不可互比', ['A 80/20｜B 30/10/60 (seed 63466)','C 10/10/80 (seed 42)｜D 每类20/10/70 (seed 1334)','不同协议的训练量不同，分数不可横比'], ['Protocol A','B / C','D'],
      '这套协议表来自本项目 benchmark.md。以后看到任何分数先问协议；拿 A 协议的 SVM 和 B 协议的 HybridSN 比大小是没有意义的。',
      ),
 ],
 code='y = [0]*900 + [1]*90 + [2]*10\npred = [0]*1000\nassert cohen_kappa_score(y, pred) == 0\n# Fit preprocessing on train; report test separately.',
 change='把错误全部集中在小类，再观察OA与AA如何变化。',
 ai='给出这份实验协议的三个反例：哪些信息可能提前来自测试集？每条指出具体变量与检查断言，不要仅回答“存在数据泄漏”。',
 verify='逐项追踪fit/transform与model selection，手算toy指标并用库核对。',
 limits=['相邻像元不是独立重复实验','标准差不直接等于显著性门槛']),

 dict(id='L03',slug='svm',title='上神经网络之前，先做一个可信基线',subtitle='SVM、特征尺度与验证调参',
 prerequisites='L02：train/val/test与指标',notebook='02_svm_baseline.ipynb',cells=['SVC','train_test_split'],assignment='A02',
 outputs=['基线配置','测试报告','核参数尺度检查'],sources=['svm','sklearn'],
 pages=[
 page('Baseline是检查器，不是稻草人', ['先确认光谱里有没有判别信息','与后续模型用同一份输入','基线成绩：协议A实测 0.85'], ['Data sanity','Same input','0.85 @ 2050'],
      '基线不是用来踩的。0.85 是 notebook 02 在 2050 个测试像元上的实测值——后面任何模型先问一句：比基线同协议高多少？',
      run=('pipe.score(X_test, y_test)  # 协议A', '0.85')),
 page('从cube到样本表', ['每个有标注像元一行','类别列不能留在特征中','保留坐标用于预测回贴'], ['Cube','(samples,bands)','Labels + positions'],
      '10249 行、200 列特征来自上一课的实测统计。CSV是存储选择，不是算法需求。',
      run=('X.shape, y.shape', '((10249, 200), (10249,))')),
 page('RBF把距离变成相似度', ['距离大：相似度趋零','gamma大：局部影响范围窄','C控制拟合与正则的权衡'], ['x','Squared distance','Kernel similarity'],
      '先手算再上库：同样 d²=100，gamma 差 100 倍，相似度一个还能用、一个已经归零——这就是后面塌缩的伏笔。',
      math=r'K(x, x\') = \exp(-\gamma \, \| x - x\' \|^2)',
      run=('np.exp(-0.01*100), np.exp(-1*100)', '(0.368, 3.7e-44)')),
 page('尺度塌缩：教科书网格全灭', ['原始DN方差≈2.5e6，d²百万级','gamma=1e-4 时 exp(-5e2) 下溢为 0','16 格网格全部塌缩到 24.0%(多数类)'], ['网格 1e-4…1e-1','全部 24.0%','scale ≈ 2e-9'],
      '本项目真实踩过的坑：按教科书范围调参，16 格全是同一个数。原因不是模型，是 exp 下溢——重新定标 [1e-10, 1e-7] 才恢复。gamma=scale 的实算值与经验一致。',
      run=("1/(200*X.var())  # gamma='scale'", '2.0e-09')),
 page('调参只能看验证证据', ['固定候选范围与预算','Pipeline内拟合变换','测试不参与选C/gamma'], ['Train fit','Val compare','Frozen test'],
      '网格边缘最佳提示范围可能不足，不证明下一格必然更好。'),
 page('换个特征，混淆结构就变', ['同一SVC，先跑原始200波段','再用PCA特征重跑一次','逐类错误分布明显不同'], ['Raw DN features','PCA features','Per-class errors'],
      '本图来自notebook 02的降维特征实验，与原始波段混淆矩阵同框对照。结论不是“PCA更好”，而是特征与预处理改变基线行为，报告必须写清用了哪种特征。',image=('02_svm_baseline.ipynb','ff083796-156f-45dd-8d43-c6eefa8ae068',0)),
 ],
 code='pipe = make_pipeline(StandardScaler(), SVC(C=10))\npipe.fit(X_train, y_train)\nval_pred = pipe.predict(X_val)\n# Freeze choices before predicting X_test.',
 change='固定gamma，特征乘10；再用gamma/100核对相似度是否恢复。',
 ai='从给定仓库片段提取SVM实验参数表，每个值附文件/行或变量名。找不到的项写unknown，不推测默认设置等于论文设置。',
 verify='逐个对应入口参数，核对PCA/scaler的fit范围，不按test选择配置。',
 limits=['默认超参排名不是方法上限','一次最优成绩不能替代多次复现']),

 dict(id='L04',slug='patch',title='一个像元怎样变成模型输入？',subtitle='中心、邻域、padding与坐标',
 prerequisites='L01/L02',notebook='03_hybridsn_baseline.ipynb',cells=['PatchSet','__getitem__'],assignment='A03',
 outputs=['patch提取断言','输入shape表','空间重叠说明'],sources=['pytorch'],
 pages=[
 page('邻域是输入，中心是监督', ['彩色块：有标注的中心像元','黑色：未标注位置','patch取邻域观测、中心标签'], ['Center label','Neighborhood','Unlabeled background'],
      '叠加图来自notebook 03：GT色块叠在真彩色上。让学生任指一个色块，问它的9×9邻域里有多少黑色未标注位置。',image=('03_hybridsn_baseline.ipynb','cell5',2)),
 page('先在toy数组上手算', ['5×5数组按行编号','中心(2,2)切3×3','边角需要明确padding规则'], ['Coordinate','Radius 1','3×3 patch'],
      '让学生读出中心值12，检查切片中间也是12。',math=r'p = \frac{s-1}{2} \qquad \mathrm{center} = (r{+}p,\ c{+}p)',
      run=('padded[2:5, 2:5][1, 1]', '12')),
 page('三次shape变化', ['HWC是数据读取布局','CHW是2D卷积布局','batch维由loader增加'], ['(9,9,12)','(12,9,9)','(B,12,9,9)'],
      'transpose不是随意reshape；数值位置必须对应。',
      run=('patch.transpose(2, 0, 1).shape', '(12, 9, 9)')),
 page('零填充不是零反射率地物', ['边缘观测缺失需要约定','PCA后0表示变换空间原点','更换reflect是实验变量'], ['Constant','Reflect','Controlled comparison'],
      '同一中心位置对比两种padding，不能把更漂亮的边界当性能证明。'),
 page('回贴map必须有位置证据', ['预测按原坐标写回','背景不评估，显示为黑色','全图显示不等于测试成绩'], ['Prediction map','Background masked','Test metrics separate'],
      '全图预测与mask后结果都来自notebook 03推理cell。shuffle后仅reshape、不保存坐标是常见错误。',image=('03_hybridsn_baseline.ipynb','cell18',1)),
 page('patch 重叠：这不是小事', ['错开1像素的两个9×9窗口共享 72/81','10%训练时 patch 重叠率 60–89%','中心不同 ≠ 观测独立'], ['Overlap 72/81','60–89%','Not independent'],
      '本项目量化过的泄漏：随机划分下相邻窗口几乎全共享。测试分高的解释力因此大打折扣；严格做法是空间不交划分（代价是类别覆盖不均）。',
      run=('8*9/81  # 相邻窗口共享比例', '0.889')),
 ],
 code='patch = padded[r:r+size, c:c+size]\nassert np.allclose(patch[p,p], cube[r,c])\nchw = patch.transpose(2,0,1)\n# Keep original (r,c) alongside each prediction.',
 change='检查四个角、中心、奇数size；偶数输入应报错或明确中心定义。',
 ai='为这个patch函数设计边界测试，用5×5可手算数组。给出输入、期望值和断言；不要用被测函数自身生成期望答案。',
 verify='手算首末坐标和中心值，确保测试不是循环证明。',
 limits=['patch重叠改变评估问题','更大窗口不保证更好']),

 dict(id='L05',slug='cnn',title='1D、2D、3D：到底沿哪个轴卷积？',subtitle='核、通道、感受野与计算',
 prerequisites='L04：张量轴与patch',notebook='05_2d_cnn_teaching.ipynb',cells=['SpectralSpatialCNN2D'],assignment='A03',
 outputs=['三模型shape表','含pool的感受野推导','受控对比限制'],sources=['pytorch'],
 pages=[
 page('先看轴，再看模型名字', ['1D沿波段索引','2D沿空间，聚合所有输入通道','3D沿深度与空间局部滑动'], ['1D: N,1,B','2D: N,B,H,W','3D: N,1,D,H,W'],
      '此处D可为PCA分量，不能自动称波长轴。给随机张量现场跑一次 Conv1d 看 shape。',
      run=('nn.Conv1d(1, 32, 7)(torch.randn(2,1,200)).shape', 'torch.Size([2, 32, 194])')),
 page('2D卷积也混合通道', ['groups=1时每核看全部Cin','首层 12→32、k=3：32·12·3·3+32=3488','3D区别在depth轴的局部共享'], ['Cin channels','kh × kw window','Cout features'],
      '纠正“2D只看一个通道”的常见误解。参数量当场手算，再用 weight.shape 验证。',
      math=r'\mathrm{Params} = C_{\mathrm{out}} \left( \frac{C_{\mathrm{in}}}{g}\, k_h k_w + 1 \right)',
      run=('nn.Conv2d(12, 32, 3).weight.shape', 'torch.Size([32, 12, 3, 3])')),
 page('池化也扩大感受野', ['r′=r+(k−1)·j，池化核也要算','1D 实算 7→8→16→18→26','本章初稿漏算 pooling 写成 23——已修'], ['Conv','Pool','Next conv'],
      '感受野纠错是本项目实测经历：只数卷积核会漏掉池化层。现在测试用例锁死 26（2D 同理是 12），回归测试防止再错。',
      math=r"r' = r + (k-1)\,j \qquad j' = j \times s",
      run=('assert r == 26; r', '26')),
 page('训练曲线读的是趋势', ['10轮 val 到 0.6868','test OA 0.7056，AA 只有 0.4957','Oats 16 个测试样本召回 0.0000'], ['Training loss','train acc','val acc'],
      '曲线来自notebook 05实际训练（协议C，train/val/test=1024/1025/8200）。OA 70% 而 AA 不到 50%——小类全灭的活例子，下一课展开。',
      image=('05_2d_cnn_teaching.ipynb','1a44d125',0)),
 page('预测放回空间再读', ['伪彩色观测、GT、预测三联对照','错误集中在哪些地物边界','全图显示包含训练像元'], ['Pseudo RGB','Ground truth','Prediction'],
      '本图为notebook 05预测输出（pred_map 145×145）。对照GT指出两三处错分区域，回到混淆矩阵看错误方向。',
      image=('05_2d_cnn_teaching.ipynb','feb108ea',0)),
 page('PCA空间与物理光谱分开', ['PC是线性组合，不是原始band','分量邻近不等于波长邻近','感受野不能写成nm'], ['Raw bands','PCA basis','Component depth'],
      '本项目纠过的错：曾把 PCA 分量按每分量 10nm 换算成“覆盖130nm”——错。分量是 200 个波段的线性组合，没有波长。',
      run=('pca.components_.shape', '(12, 200)')),
 ],
 code='r, jump = 1, 1\nfor kernel, stride in [(7,1),(2,2),(5,1),(2,2),(3,1)]:\n    r += (kernel-1)*jump\n    jump *= stride\nassert r == 26',
 change='固定输入，将核3换为1，分别检查参数、感受野与输出。',
 ai='根据这段模型代码生成逐层shape/感受野表，必须把池化、stride、padding写全。列出假设，不凭模型名推断。',
 verify='dummy forward检查shape；独立递推检查RF；不要把表生成器当真理。',
 limits=['理论感受野不是有效注意区域','超过patch不等于深层没有作用']),

 dict(id='L06',slug='hybridsn',title='HybridSN 的 reshape 为什么是关键？',subtitle='从经典结构到可检查的实现',
 prerequisites='L05：3D与2D轴语义',notebook='03_hybridsn_baseline.ipynb',cells=['HybridSN','forward'],assignment='A03',
 outputs=['结构映射表','形状与参数核对','一个可证伪消融问题'],sources=['hybrid','pytorch'],
 pages=[
 page('不是混合就一定更好', ['3D保留depth方向局部建模','2D继续聚合通道与空间','效果必须放在协议中测量'], ['3D features','Reshape','2D refinement'],
      '只讲有实现证据的结构，不搬未经核实论文表格数字。'),
 page('无padding，尺寸会逐层收缩', ['空间 25→23→21→19→17','PCA-15 深度 15→9→5→3','输入维数改变要重新核对'], ['25×25×15','19×19×3','17×17'],
      '现场一次 dummy forward 核对张量而不是死记表。注意 17×17 出现在 2D 卷积之后。',
      run=('features.shape  # conv3 输出', 'torch.Size([2, 64, 3, 19, 19])')),
 page('把C与D合并，不是降维', ['32×3变成96通道','19×19空间位置保留','元素数不变，不恢复原始光谱'], ['N,32,3,19,19','view','N,96,19,19'],
      '用arange小张量验证元素对应。permute和view不是同义。',
      math=r'32 \times 3 \times 19 \times 19 \;=\; 96 \times 19 \times 19',
      run=('features.reshape(2, 96, 19, 19).shape', 'torch.Size([2, 96, 19, 19])')),
 page('参数大户藏在Flatten后', ['64×17×17=18,496','首FC映射到 256','全局池化减参但会改变表示'], ['Flatten 18,496','Linear 256','Trade-off'],
      '手算 4,735,232：参数大头不是卷积而是第一个全连接。这不是"无损压缩"，是结构选择。',
      math=r'18{,}496 \times 256 + 256 = 4{,}735{,}232',
      run=('fc.weight.shape', 'torch.Size([256, 18496])')),
 page('训练过程与检查点选择', ['epoch 14 val 0.9893，本组最佳','epoch 18 train acc 瞬间崩到 0.853','最终 OA 0.9909 用的是 epoch_14 权重'], ['Loss curve','Val plateau','Best epoch'],
      '曲线来自notebook 03实际训练（协议B，测试 6150 样本）。两个干货：val 下滑后不能回头选 test 最好的轮次；训练中途崩一次再恢复也很常见——看曲线而不是看单点。',
      image=('03_hybridsn_baseline.ipynb','cell16',0)),
 page('论文、作者代码、教学代码分三列', ['核尺寸和shape逐项对齐','PCA/划分/预算单独核验','简化必须标为教学变体'], ['Paper','Author code','Course variant'],
      '官方链接是gokriznastic/HybridSN。来源未访问的表项保持待核验。本项目还撤回过一条不实归属：自定义方差惩罚不是SSRN论文的内容。',
      source='hybrid'),
 ],
 code='features = conv3(conv2(conv1(inputs.unsqueeze(1))))\nn,c,d,h,w = features.shape\nfeatures = features.reshape(n,c*d,h,w)\nlogits = classifier(conv2d(features).flatten(1))',
 change='PCA从15改30，先推断Conv2d输入通道，再用forward验证。',
 ai='只比较提供的论文段落和源码，输出差异表；每项附页码或函数名。没有来源的PCA/epoch/seed标unknown，不猜论文默认值。',
 verify='逐项读原文和源码；形状由framework核对；引用不能由搜索摘要替代。',
 limits=['教学同构不等于逐数复现','参数压缩不自动产生论文贡献']),

 dict(id='L07',slug='errors',title='OA 很高，小类为什么仍全错？',subtitle='损失、错误地图与真正的 Grad-CAM',
 prerequisites='L02/L05',notebook='15_imbalance_analysis_teaching.ipynb',cells=['loss-comparison','gradcam','maps'],assignment='A04',
 outputs=['同划分损失报告','逐类recall与错误map','类条件Grad-CAM'],sources=['focal','cam'],
 pages=[
 page('先隐藏OA，读小类召回', ['分类器可能优先满足大类','support影响估计稳定性','报告每类错误而非一行总分'], ['Class count','Per-class recall','Failure cases'],
      '引用本次Notebook输出，不沿用历史实验+8点作为承诺。',image=('15_imbalance_analysis_teaching.ipynb','loss-comparison',0)),
 page('加权CE与Focal改变什么', ['实测 CE→加权CE：OA 0.9506→0.9440','AA 0.8029→0.9345，Alfalfa 召回 0.405→0.811','用 0.7 个 OA 换 13 个 AA——取舍是真的'], ['Class weights','Hard examples','OA / AA trade-off'],
      '数字来自notebook 15同划分实测。加权不是免费的：大类让出多少，OA就掉多少；Focal依据难度、加权依据频率，两种方法不能混称。',
      math=r'w_c = \frac{N}{C\, n_c} \qquad FL = -(1 - p_t)^{\gamma} \log p_t',
      run=('aa_ce, aa_weighted  # macro recall', '(0.8029, 0.9345)')),
 page('同一split，才能读这张图', ['共享预处理与划分','固定模型与选择规则','预测图不是额外测试成绩'], ['GT','CE','Weighted CE'],
      '全图显示包含训练像元，测试错误另画。',image=('15_imbalance_analysis_teaching.ipynb','maps',0)),
 page('Grad-CAM必须真的求梯度', ['明确模型与目标类别','梯度空间均值给通道权重','加权、ReLU、插值回输入'], ['Target logit','Gradient weights','Spatial response'],
      '通道均值图不属于Grad-CAM，target换了图可能变化；不允许no_grad包住关键步骤。',math=r'\alpha_k = \frac{1}{HW} \sum_{i,j} \frac{\partial z_c}{\partial A_{ij}^{k}} \qquad \mathrm{CAM} = \mathrm{ReLU}\left(\sum_{k} \alpha_k A^{k}\right)'),
 page('失败样本也要展示', ['正确、错误、稀有类各一个','原始类ID与坐标明确','零CAM不等于“模型没看输入”'], ['Correct','Misclassified','Rare class'],
      '本图按预先规则选样，不挑好看案例。',image=('15_imbalance_analysis_teaching.ipynb','gradcam',0),source='cam'),
 page('解释图不是因果证明', ['相关热区可以生成假设','遮挡也可能造成分布外输入','结合指标、错误图和受控实验'], ['Attribution','Perturbation','Limitations'],
      't-SNE、CAM各有条件，论文分析不能仅靠颜色叙事。'),
 ],
 code='cams, logits = grad_cam(model, layer, inputs, targets)\nassert cams.shape == inputs.shape[:1] + inputs.shape[-2:]\nassert torch.isfinite(cams).all()\n# Compare predicted vs alternative target class.',
 change='固定同一patch，只更换Grad-CAM目标类别，解释哪些能推断、哪些不能。',
 ai='依据给定recall表和错误图提出三种可检验假设，每条列控制变量和反例。不要把热力图高亮说成因果证据，不补造实验结果。',
 verify='核对目标梯度真实存在；假设另做实验；保留零响应与失败样本。',
 limits=['降低大类权重可能损失OA','热图插值不增加解释分辨率']),

 dict(id='L08',slug='fewshot',title='5-shot 的五个样本，究竟怎么算？',subtitle='Meta-training / Support / Query',
 prerequisites='L04/L05；理解特征向量',notebook='16_protonet_teaching.ipynb',cells=['protocol','episode','prototype-math','evaluation','maps'],assignment='A05',
 outputs=['类集合与标签预算表','episode位置清单','原型分类与K对照'],sources=['proto'],
 pages=[
 page('25个标签，不是全部训练预算', ['"25个标签"只是单次任务的support','encoder 用 6 类全部标注训练','meta-test 5 类：12,13,14,15,16'], ['Meta-training labels','25 support labels','Query evaluation'],
      '这是本项目纠正过的话术："只25个标签就92%"不成立——类划分本身用了大量标注。完整预算=encoder标注+support。',
      run=("META['test']", '[12, 13, 14, 15, 16]')),
 page('同类少标注与未见类学习', ['same-class：像元分开','class-disjoint：类别分开','两者都不自动空间独立'], ['Meta-train','Meta-val','Meta-test'],
      '展示当前6/5/5显式划分，说明同场景patch仍可共享无标签上下文。'),
 page('Support和Query不能串门', ['每轮抽5类','支持集建原型，query算损失/指标','不足N类必须报错'], ['Sample classes','Support K','Query Q'],
      '图例明确圆圈/叉号，打印原图坐标与无交集断言。',image=('16_protonet_teaching.ipynb','episode',0)),
 page('用二维例子算原型', ['类1支持点(0,0),(2,0) → 原型(1,0)','类2支持点(8,0),(10,0) → 原型(9,0)','query=(4,0)：距离9 vs 25，归类1'], ['Prototype (1,0)','Query (4,0)','Prototype (9,0)'],
      '均值原型后平方距离9和25，负号使近者logit更大。手算完再对代码。',
      math=r'c_k = \mathrm{mean}_i\, f(x_i) \qquad \mathrm{logits} = - \| f(q) - c_k \|^2',
      run=('c1, c2 = (0+2)/2, (8+10)/2', '(1.0, 9.0)')),
 page('K对照要用同一encoder', ['冻结已验证checkpoint','固定类池与配对query','任务重复不是新数据集证据'], ['1-shot','5-shot','10-shot'],
      '不能把分别训练的模型曲线解释成纯K变化效果。',image=('16_protonet_teaching.ipynb','evaluation',0)),
 page('全图map只是任务外示范', ['只存在五类原型','其他类会被强制分到五类','不能用这张图声称16类泛化'], ['Support classes','Forced assignment','Display only'],
      'GT用于显示，不进入推理；本次map特意展示封闭输出空间的局限。',image=('16_protonet_teaching.ipynb','maps',0)),
 ],
 code='protos = stack([support[y==c].mean(0) for c in classes])\nlogits = -((query[:,None]-protos[None])**2).sum(-1)\nloss = cross_entropy(logits, query_y)\nassert not set(support_ids) & set(query_ids)',
 change='固定query，K从1增至5；个别任务下降也如实记录。',
 ai='审计这份few-shot配置的标签预算、类集合与support/query信息流。输出需执行的断言，禁止把单episode的support数量写成总训练标注量。',
 verify='验证类集合不交、像元不交、独立采样器；核对BN是否适应query。',
 limits=['同场景类别不交≠空间外推','样本相关时均值方差不必按1/K缩小']),

 dict(id='L09',slug='openset',title='模型能学会说“我不知道”吗？',subtitle='分数、阈值、拒识地图与代价',
 prerequisites='L02/L05；原型概念',notebook='17_openset_teaching.ipynb',cells=['protocol','scores','calibration','evaluation','maps'],assignment='A06',
 outputs=['验证阈值配置','白色未知map','误拒/漏检和已知可用性报告'],sources=['msp','openmax'],
 pages=[
 page('未知、背景、难样本不是同一个概念', ['未知：训练未监督的类别','背景：没有标签的像元','难样本：也可能属于已知类'], ['Known classes','Held-out unknown','Unlabeled background'],
      '默认稀有类留出只是教学split，不能代表所有未知地物。'),
 page('Softmax没有未知输出槽', ['已知logits永远归一化','高置信度不保证已知','仍可以用其分数做检测'], ['Known logits','Softmax','Max probability'],
      '用(2,1)手算MSP .731，整体平移不变。阈值不是拍脑袋：取已知类验证分数的95%分位，实测 0.2456。',
      math=r's_{\mathrm{MSP}}(x) = 1 - \max\, \mathrm{softmax}(z(x))',
      run=("tau['msp']  # val 95% 分位", '0.2456')),
 page('距离是另一种读模型的方式', ['用已知训练类建原型','特征与标签保持配对','最近原型距离越大越未知'], ['Training embeddings','Class means','Nearest distance'],
      '已知类监督encoder，不冒称加载了ProtoNet。距离阈值同样来自验证分位：实测 5.5572。距离也可能失败。',
      math=r's_{\mathrm{dist}}(x) = \min_k \| f(x) - c_k \|_2',
      run=("tau['distance']", '5.5572')),
 page('阈值在测试前冻结', ['known validation校准95%接受率','不使用unknown test选阈值','目标接受率不保证实际测试值'], ['Train model','Val threshold','Frozen test'],
      '本课模型选择与校准共享val需披露，不声称独立校准保证。',
      math=r'\tau = Q_{0.95}(s_{\mathrm{val}}) \qquad s > \tau \;\Rightarrow\; \mathrm{reject}'),
 page('排序能力不等于部署准确率', ['实测 AUROC：MSP 0.849 vs 距离 0.851','几乎相同——旧稿“距离远胜”已撤回','95%目标下实际正确接受约 0.920'], ['AUROC','Known utility','Unknown recall'],
      '这是本项目自己的实证纠错：两方法在当前设置下排序能力相当，差距只在阈值处的代价分配。旧课件“距离远胜”的话术撤回。',
      image=('17_openset_teaching.ipynb','evaluation',0)),
 page('白色越多，不一定越好', ['白色表示拒识，不保证正确','黑色是未标注背景','对照未知GT和错误图'], ['Open-set GT','MSP map','Distance map'],
      '先看图，再解释known false rejection与unknown miss。',image=('17_openset_teaching.ipynb','maps',0)),
 page('把误拒、漏检、错分拆开', ['全部拒绝会损失已知可用性','未知漏检会被强制命名','必须同时报告三种代价'], ['False rejection','Unknown miss','Known wrong class'],
      '深蓝=指定错误；灰色=未评估。计数来自固定测试集合。',image=('17_openset_teaching.ipynb','maps',1)),
 ],
 code='tau = np.quantile(known_val_scores, 0.95)\nrejected = test_scores > tau\n# Unknown = 17 (white), background = 0 (black)\n# Test labels are used only for evaluation.',
 change='接受率.95改.90，只用validation重新校准，先预测误拒与漏检方向。',
 ai='检查这段开集代码的数据流：哪些量只能由train或val计算？为每个阈值写来源；禁止从test标签、AUROC最佳点选择部署阈值。',
 verify='固定test前冻结阈值；核对类映射及unknown score方向。',
 limits=['高AUROC不保证选定阈值好用','OpenMax为概念扩展，未冒称本课已复现']),

 dict(id='L10',slug='research',title='一次实验怎样变成可信研究证据？',subtitle='阅读、假设、对照、写作',
 prerequisites='L02与至少一个模型实践',notebook=None,cells=['run_config.json','metrics.json','source-audit.md'],assignment='A06',
 outputs=['半页研究登记','来源差异表','受限结果段落'],sources=['reading','repro'],
 pages=[
 page('研究不是把模块加在一起', ['问题必须能被否证','baseline要对齐协议','失败也能形成可检查结论'], ['Question','Hypothesis','Evidence'],
      '用课程负结果教怎么审计，不拿不完整复现否定原论文。'),
 page('阅读先区分三个层次', ['原文贡献与设定','官方代码的实际实现','课程简化和自定义扩展'], ['Paper','Code','Teaching variant'],
      '没有原文证据时停在待核验；不能给编造机制套“待核对”脚注。'),
 page('一次只改一个有解释的变量', ['固定数据与选择规则','记录预算和环境','模型实现要支持消融开关'], ['Baseline','One change','Matched comparison'],
      '同epoch不一定同优化预算；记录更新次数和算力目标。'),
 page('三颗种子不是统计魔法', ['先看每颗种子的配对差','说明重复单位和相关性','std不是显著性阈值'], ['Run pairs','Delta distribution','Scope of evidence'],
      '示例 d=[-0.1,-0.2,-0.1]：均值-0.133、样本std 0.058。三次同号不等于显著——说显著要先定检验和功效。',
      math=r'\Delta_i = \mathrm{m}_{\mathrm{var}}(\mathrm{seed}_i) - \mathrm{m}_{\mathrm{base}}(\mathrm{seed}_i)',
      run=('np.mean(d), np.std(d, ddof=1)  # d=[-.1,-.2,-.1]', '(-0.133, 0.058)')),
 page('把每一句结论绑到证据', ['观察：这次得到了什么','解释：需要验证的假设','限制：哪些任务不能外推'], ['Observation','Hypothesis','Limitation'],
      '示范把“模块证明有效”改成限定条件的描述。'),
 page('论文骨架是证据的目录', ['Method：公式与实现','Experiments：协议与对照','Discussion：失败与局限'], ['Method','Experiments','Discussion'],
      '先写确定的实验和方法，再写摘要引言；模板编译需实际验证。'),
 ],
 code='record = {"split": ..., "seed": ..., "preprocess_fit": ...}\n# Archive config + predictions + source revision.\n# Write observation separately from explanation.\n# Never tune on the final test results.',
 change='把一句过度结论改写为观察、解释假设、适用域三句话。',
 ai='仅根据给定实验表润色英文结果段落。不得新增数字、引用或因果主张；每句话附证据行号，证据不足写[needs evidence]，保留负结果。',
 verify='逐句核对数值和来源；遵守投稿方AI披露政策，不上传未授权资料。',
 limits=['没有增益不等于方法无效','完整课程不等于论文已完成']),
]
