"""Render the HSI-Learning video intro (片头) to MP4 for Bilibili.

The animation lives in ``video/intro/intro.html`` and ends on the exact cover
layout of the classroom decks (``scripts/build_course_slides.js``). Lesson text
comes from ``slides/src/course_content.py``; each cover's short title and hero
figure placement come from ``slides/lesson-manifest.json`` (written by the deck
build); the curve is the real mean spectrum of the labelled Indian Pines pixels.
So nothing is typed twice: rebuild the decks, then rebuild the intro.

Steps: export ``intro-data.js`` -> step ``renderFrame(t)`` in headless
Chromium -> pipe PNG frames into ffmpeg (H.264 + AAC, yuv420p, faststart).

    pip install -r requirements-video.txt
    python -m playwright install chromium          # once
    python scripts/build_video_intro.py            # series + every lesson (L00..L10, L05A)
    python scripts/build_video_intro.py --only series L03 --fps 30
    python scripts/build_video_intro.py --size 2160 --audio silent

ffmpeg must be on PATH (or pass --ffmpeg). Outputs go to video/intro/renders/.
"""
from __future__ import annotations

import argparse
import json
import math
import shutil
import subprocess
import sys
import tempfile
import wave
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
INTRO = ROOT / 'video' / 'intro'
sys.path.insert(0, str(ROOT / 'slides' / 'src'))
from course_content import LESSONS  # noqa: E402

SERIES = dict(
    id='全 12 课',
    cover_title='高光谱图像分类\n从零到一',
    question_label='课程主线',
    question='数据 → 经典模型 → 小样本 → 开集 → 科研写作',
    subtitle='经典方法  ·  关键推导  ·  真实代码  ·  可检验实验',
    footer='github.com/masskx/HSI-Learning  ·  B站 学术蒟蒻',
    hero_from='L01',
)
CAPTION = 'Indian Pines · 标注像元平均光谱 · 200 bands'
SAMPLE_RATE = 48000


# ------------------------------------------------------------------ data
def mean_spectrum() -> list[float]:
    """Mean spectrum of labelled Indian Pines pixels, min-max scaled to [0, 1]."""
    cache = INTRO / 'spectrum.json'
    try:
        from scipy.io import loadmat
        cube = loadmat(ROOT / 'dataset' / 'Indian_pines_corrected.mat')['indian_pines_corrected']
        gt = loadmat(ROOT / 'dataset' / 'Indian_pines_gt.mat')['indian_pines_gt']
        m = cube[gt > 0].astype(np.float64).mean(axis=0)
        values = [round(float(v), 4) for v in (m - m.min()) / (m.max() - m.min())]
        cache.write_text(json.dumps(values) + '\n', encoding='utf-8')
        return values
    except (ImportError, OSError, KeyError) as exc:
        if not cache.exists():
            raise SystemExit(f'cannot compute spectrum ({exc}) and no cache at {cache}')
        print(f'[spectrum] using cached {cache.name} ({exc.__class__.__name__})')
        return json.loads(cache.read_text(encoding='utf-8'))


def cover_heroes() -> dict:
    """Cover title + hero card geometry per lesson, as recorded by the deck build."""
    manifest = json.loads((ROOT / 'slides' / 'lesson-manifest.json').read_text(encoding='utf-8'))
    heroes_dir = INTRO / 'heroes'
    heroes_dir.mkdir(exist_ok=True)
    out = {}
    for deck in manifest['decks']:
        cover = deck['pages'][0]
        hero = cover.get('hero')
        if 'cover_title' not in cover or not hero:
            raise SystemExit('lesson-manifest.json has no cover data; rebuild the decks with '
                             'scripts/build_course_slides.py first.')
        target = heroes_dir / f"{deck['id']}.png"
        source = ROOT / hero['image']
        if source.exists():
            shutil.copyfile(source, target)
        elif not target.exists():
            raise SystemExit(f'missing hero figure {source}; run scripts/export_slide_content.py')
        out[deck['id']] = dict(cover_title=cover['cover_title'],
                               hero=dict(src=f"heroes/{deck['id']}.png", card=hero['card'], figure=hero['figure']))
    return out


def export_data() -> dict:
    covers = cover_heroes()
    lessons = {
        les['id']: dict(id=les['id'], question_label='本课问题', question=les['title'],
                        subtitle=les['subtitle'], footer='先修  ·  ' + les['prerequisites'],
                        **covers[les['id']])
        for les in LESSONS
    }
    series = {k: v for k, v in SERIES.items() if k != 'hero_from'}
    series['hero'] = covers[SERIES['hero_from']]['hero']
    data = dict(spectrum=mean_spectrum(), caption=CAPTION, series=series, lessons=lessons)
    (INTRO / 'intro-data.js').write_text(
        '// Generated by scripts/build_video_intro.py from course_content.py and slides/lesson-manifest.json.\n'
        'window.INTRO_DATA = ' + json.dumps(data, ensure_ascii=False, indent=1) + ';\n',
        encoding='utf-8')
    return data


# ------------------------------------------------------------------ audio
def _tone(t, freq, start, decay, gain, attack=0.008):
    """Soft sine pluck with a short attack and exponential decay."""
    x = t - start
    env = np.where(x < 0, 0.0, np.minimum(x / attack, 1.0) * np.exp(-np.maximum(x, 0) / decay))
    return gain * env * (np.sin(2 * np.pi * freq * x) + 0.18 * np.sin(4 * np.pi * freq * x))


def synth_audio(duration: float, path: Path, mode: str) -> None:
    """Quiet sound sting synced to the timeline in intro.html (or silence)."""
    n = int(duration * SAMPLE_RATE)
    t = np.arange(n) / SAMPLE_RATE
    left = np.zeros(n)
    right = np.zeros(n)
    if mode == 'chime':
        # Harp-like pentatonic rise while the spectrum draws (0.25-1.45 s), panned L->R.
        scale = [0, 2, 4, 7, 9]
        notes = 16
        for k in range(notes):
            u = k / (notes - 1)
            semis = scale[k % 5] + 12 * (k // 5)
            freq = 392.0 * 2 ** (semis / 12)
            s = _tone(t, freq, 0.25 + 1.2 * u ** 1.1, 0.55, 0.11 * (1 - 0.35 * u))
            left += s * math.cos(u * math.pi / 2)
            right += s * math.sin(u * math.pi / 2)
        # Soft air swell while the spectrum settles into the cover band (2.8-3.8 s).
        rng = np.random.default_rng(7)
        noise = rng.standard_normal(n)
        for _ in range(3):  # cheap low-pass
            noise = np.convolve(noise, np.ones(24) / 24, mode='same')
        swell = np.clip((t - 2.75) / 0.8, 0, 1) ** 2 * np.exp(-np.maximum(t - 3.55, 0) / 0.25)
        left += 0.9 * noise * swell
        right += 0.9 * np.roll(noise, 211) * swell
        # Warm resolving chord as the cover title lands (3.6 s).
        for freq, g in [(130.81, .20), (196.0, .14), (329.63, .11), (493.88, .07), (587.33, .06)]:
            for det, pan in [(1.0, .5), (1.003, .35), (0.997, .65)]:
                s = _tone(t, freq * det, 3.6, 1.9, g / 3, attack=0.03)
                left += s * (1 - pan)
                right += s * pan
        # Small room: a few decaying echoes.
        for ms, g in [(37, .22), (71, .16), (113, .11), (167, .07)]:
            d = int(ms * SAMPLE_RATE / 1000)
            left[d:] += g * right[:-d]
            right[d:] += g * left[:-d]
        fade = np.clip((duration - t) / 0.6, 0, 1)
        left *= fade
        right *= fade
        peak = max(np.abs(left).max(), np.abs(right).max(), 1e-9)
        scale_to = 10 ** (-6 / 20) / peak  # -6 dBFS peak
        left *= scale_to
        right *= scale_to
    pcm = (np.stack([left, right], axis=1) * 32767).astype('<i2')
    with wave.open(str(path), 'wb') as w:
        w.setnchannels(2)
        w.setsampwidth(2)
        w.setframerate(SAMPLE_RATE)
        w.writeframes(pcm.tobytes())


# ------------------------------------------------------------------ video
def render(variant: str, args, browser, out_dir: Path) -> Path:
    scale = args.size / 1080
    page = browser.new_page(viewport={'width': 1920, 'height': 1080}, device_scale_factor=scale)
    query = 'capture=1' + ('' if variant == 'series' else f'&lesson={variant}')
    page.goto((INTRO / 'intro.html').as_uri() + '?' + query)
    if args.font_css:
        page.add_style_tag(path=str(args.font_css))
    page.evaluate('document.fonts.ready')
    # Warm every glyph so lazily loaded font subsets are ready before frame 0.
    page.evaluate('INTRO.renderFrame(INTRO.DURATION)')
    page.evaluate('document.fonts.ready')
    page.wait_for_timeout(300)
    duration = page.evaluate('INTRO.DURATION') + args.tail
    frames = round(duration * args.fps)

    name = 'HSI-Learning-intro' if variant == 'series' else f'HSI-Learning-intro-{variant}'
    out = out_dir / f'{name}-{args.size}p{args.fps}.mp4'
    with tempfile.TemporaryDirectory() as tmp:
        wav = Path(tmp) / 'sting.wav'
        synth_audio(frames / args.fps, wav, args.audio)
        cmd = [args.ffmpeg, '-y', '-loglevel', 'error',
               '-f', 'image2pipe', '-framerate', str(args.fps), '-c:v', 'png', '-i', '-',
               '-i', str(wav),
               '-c:v', 'libx264', '-preset', 'slow', '-crf', str(args.crf), '-tune', 'animation',
               '-pix_fmt', 'yuv420p', '-profile:v', 'high',
               '-colorspace', 'bt709', '-color_primaries', 'bt709', '-color_trc', 'bt709',
               '-c:a', 'aac', '-b:a', '192k', '-ar', str(SAMPLE_RATE),
               '-shortest', '-movflags', '+faststart', str(out)]
        proc = subprocess.Popen(cmd, stdin=subprocess.PIPE)
        for f in range(frames):
            page.evaluate(f'INTRO.renderFrame({f / args.fps})')
            proc.stdin.write(page.screenshot(type='png'))
        if args.stills:
            for ts in (0.9, 2.2, 3.3, 4.2, duration):
                page.evaluate(f'INTRO.renderFrame({ts})')
                page.screenshot(path=str(out_dir / f'{name}-t{ts:.1f}.png'))
        proc.stdin.close()
        if proc.wait():
            raise SystemExit(f'ffmpeg failed for {variant}')
    page.close()
    print(f'[intro] {out}  ({frames} frames, {out.stat().st_size / 1e6:.1f} MB)')
    return out


def main() -> None:
    ids = [les['id'] for les in LESSONS]
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--only', nargs='+', metavar='VARIANT', help=f'series and/or lesson ids ({ids[0]}..{ids[-1]})')
    ap.add_argument('--fps', type=int, default=60)
    ap.add_argument('--size', type=int, default=1080, choices=[1080, 1440, 2160], help='output height')
    ap.add_argument('--crf', type=int, default=14)
    ap.add_argument('--tail', type=float, default=0.5, help='extra seconds held on the last frame')
    ap.add_argument('--audio', choices=['chime', 'silent'], default='chime')
    ap.add_argument('--font-css', type=Path, help='optional @font-face CSS when Microsoft YaHei is not installed')
    ap.add_argument('--stills', action='store_true', help='also save key-frame PNGs for review')
    ap.add_argument('--ffmpeg', default=shutil.which('ffmpeg') or 'ffmpeg')
    ap.add_argument('--out', type=Path, default=INTRO / 'renders')
    ap.add_argument('--data-only', action='store_true', help='only regenerate intro-data.js')
    args = ap.parse_args()

    export_data()
    if args.data_only:
        return
    variants = args.only or ['series', *ids]
    unknown = [v for v in variants if v != 'series' and v not in ids]
    if unknown:
        raise SystemExit(f'unknown variant(s): {unknown}')
    if not shutil.which(args.ffmpeg) and not Path(args.ffmpeg).exists():
        raise SystemExit('ffmpeg not found; install it or pass --ffmpeg PATH')
    args.out.mkdir(parents=True, exist_ok=True)

    from playwright.sync_api import sync_playwright
    with sync_playwright() as pw:
        browser = pw.chromium.launch()
        for v in variants:
            render(v, args, browser, args.out)
        browser.close()


if __name__ == '__main__':
    main()
